name: docker

on:
  push:
    branches:
      - 'main'
    patchs:
        - app/**

jobs:
 docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 
        uses: docker/build-push-action@v5
        working-directory: app
        with:
          registry: docker.io
          image: danielmagevski/app
          push: true
          tags: danielmagevski/app:latest
          
 
