name: Docker

on:
  push:
    branches:
      - 'main'
    paths:
      - app/**

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          registry: docker.io
          image: danielmagevski/nginx
          push: true
          tags: danielmagevski/nginx:latest
  
  docker-deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      -
        name:
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ secrets.IP_HOST }} "ls"
      #-
       # name:
        #  run: |
        #ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ secrets.IP_HOST }} "docker stack deploy -c /path/to/your-stack-file.yml your-stack-name"
